const musicCatalog = [
  {
    "id": "58ge6dfP91o9oXMzq3XkIS",
    "title": "505",
    "artist": "Arctic Monkeys",
    "album": "Favourite Worst Nightmare (Standard Version)",
    "year": "2007",
    "genre": "rock",
    "duration": "4:13",
    "popularity": 85,
    "preview_url": null,
    "coverImage": "images/58ge6dfP91o9oXMzq3XkIS.jpg",
    "spotify_url": "https://open.spotify.com/track/58ge6dfP91o9oXMzq3XkIS"
  },
  {
    "id": "2QjOHCTQ1Jl3zawyYOpxh6",
    "title": "Sweater Weather",
    "artist": "The Neighbourhood",
    "album": "I Love You.",
    "year": "2013",
    "genre": "rock",
    "duration": "4:00",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/2QjOHCTQ1Jl3zawyYOpxh6.jpg",
    "spotify_url": "https://open.spotify.com/track/2QjOHCTQ1Jl3zawyYOpxh6"
  },
  {
    "id": "0ofHAoxe9vBkTCp2UQIavz",
    "title": "Dreams - 2004 Remaster",
    "artist": "Fleetwood Mac",
    "album": "Rumours (Super Deluxe)",
    "year": "1977",
    "genre": "rock",
    "duration": "4:17",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/0ofHAoxe9vBkTCp2UQIavz.jpg",
    "spotify_url": "https://open.spotify.com/track/0ofHAoxe9vBkTCp2UQIavz"
  },
  {
    "id": "003vvx7Niy0yvhvHt4a68B",
    "title": "Mr. Brightside",
    "artist": "The Killers",
    "album": "Hot Fuss",
    "year": "2004",
    "genre": "rock",
    "duration": "3:42",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/003vvx7Niy0yvhvHt4a68B.jpg",
    "spotify_url": "https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B"
  },
  {
    "id": "6Qyc6fS4DsZjB2mRW9DsQs",
    "title": "Iris",
    "artist": "The Goo Goo Dolls",
    "album": "Dizzy up the Girl",
    "year": "1998",
    "genre": "rock",
    "duration": "4:49",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/6Qyc6fS4DsZjB2mRW9DsQs.jpg",
    "spotify_url": "https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs"
  },
  {
    "id": "1CS7Sd1u5tWkstBhpssyjP",
    "title": "Take Me to Church",
    "artist": "Hozier",
    "album": "Hozier (Expanded Edition)",
    "year": "2014",
    "genre": "rock",
    "duration": "4:01",
    "popularity": 83,
    "preview_url": null,
    "coverImage": "images/1CS7Sd1u5tWkstBhpssyjP.jpg",
    "spotify_url": "https://open.spotify.com/track/1CS7Sd1u5tWkstBhpssyjP"
  },
  {
    "id": "2tznHmp70DxMyr2XhWLOW0",
    "title": "Cigarette Daydreams",
    "artist": "Cage The Elephant",
    "album": "Melophobia",
    "year": "2013",
    "genre": "rock",
    "duration": "3:28",
    "popularity": 83,
    "preview_url": null,
    "coverImage": "images/2tznHmp70DxMyr2XhWLOW0.jpg",
    "spotify_url": "https://open.spotify.com/track/2tznHmp70DxMyr2XhWLOW0"
  },
  {
    "id": "70LcF31zb1H0PyJoS1Sx1r",
    "title": "Creep",
    "artist": "Radiohead",
    "album": "Pablo Honey",
    "year": "1993",
    "genre": "rock",
    "duration": "3:58",
    "popularity": 90,
    "preview_url": null,
    "coverImage": "images/70LcF31zb1H0PyJoS1Sx1r.jpg",
    "spotify_url": "https://open.spotify.com/track/70LcF31zb1H0PyJoS1Sx1r"
  },
  {
    "id": "0d28khcov6AiegSCpG5TuT",
    "title": "Feel Good Inc.",
    "artist": "Gorillaz, De La Soul",
    "album": "Demon Days",
    "year": "2005",
    "genre": "rock",
    "duration": "3:42",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/0d28khcov6AiegSCpG5TuT.jpg",
    "spotify_url": "https://open.spotify.com/track/0d28khcov6AiegSCpG5TuT"
  },
  {
    "id": "5TgEJ62DOzBpGxZ7WRsrqb",
    "title": "Work Song",
    "artist": "Hozier",
    "album": "Hozier (Expanded Edition)",
    "year": "2014",
    "genre": "rock",
    "duration": "3:49",
    "popularity": 82,
    "preview_url": null,
    "coverImage": "images/5TgEJ62DOzBpGxZ7WRsrqb.jpg",
    "spotify_url": "https://open.spotify.com/track/5TgEJ62DOzBpGxZ7WRsrqb"
  },
  {
    "id": "5XeFesFbtLpXzIVDNQP22n",
    "title": "I Wanna Be Yours",
    "artist": "Arctic Monkeys",
    "album": "AM",
    "year": "2013",
    "genre": "rock",
    "duration": "3:03",
    "popularity": 93,
    "preview_url": null,
    "coverImage": "images/5XeFesFbtLpXzIVDNQP22n.jpg",
    "spotify_url": "https://open.spotify.com/track/5XeFesFbtLpXzIVDNQP22n"
  },
  {
    "id": "42T2QQv3xgBlpQxaSP7lnK",
    "title": "One Last Breath",
    "artist": "Creed",
    "album": "Weathered",
    "year": "2001",
    "genre": "rock",
    "duration": "3:58",
    "popularity": 85,
    "preview_url": null,
    "coverImage": "images/42T2QQv3xgBlpQxaSP7lnK.jpg",
    "spotify_url": "https://open.spotify.com/track/42T2QQv3xgBlpQxaSP7lnK"
  },
  {
    "id": "2hnMS47jN0etwvFPzYk11f",
    "title": "Santeria",
    "artist": "Sublime",
    "album": "Sublime",
    "year": "1996",
    "genre": "rock",
    "duration": "3:02",
    "popularity": 83,
    "preview_url": null,
    "coverImage": "images/2hnMS47jN0etwvFPzYk11f.jpg",
    "spotify_url": "https://open.spotify.com/track/2hnMS47jN0etwvFPzYk11f"
  },
  {
    "id": "76JKIsdKrAfWUMjaA0u7v5",
    "title": "Too Sweet",
    "artist": "Hozier",
    "album": "Unreal Unearth: Unaired",
    "year": "2024",
    "genre": "rock",
    "duration": "4:11",
    "popularity": 81,
    "preview_url": null,
    "coverImage": "images/76JKIsdKrAfWUMjaA0u7v5.jpg",
    "spotify_url": "https://open.spotify.com/track/76JKIsdKrAfWUMjaA0u7v5"
  },
  {
    "id": "5TTGoX70AFrTvuEtqHK37S",
    "title": "No. 1 Party Anthem",
    "artist": "Arctic Monkeys",
    "album": "AM",
    "year": "2013",
    "genre": "rock",
    "duration": "4:03",
    "popularity": 90,
    "preview_url": null,
    "coverImage": "images/5TTGoX70AFrTvuEtqHK37S.jpg",
    "spotify_url": "https://open.spotify.com/track/5TTGoX70AFrTvuEtqHK37S"
  },
  {
    "id": "6K4t31amVTZDgR3sKmwUJJ",
    "title": "The Less I Know The Better",
    "artist": "Tame Impala",
    "album": "Currents",
    "year": "2015",
    "genre": "rock",
    "duration": "3:36",
    "popularity": 87,
    "preview_url": null,
    "coverImage": "images/6K4t31amVTZDgR3sKmwUJJ.jpg",
    "spotify_url": "https://open.spotify.com/track/6K4t31amVTZDgR3sKmwUJJ"
  },
  {
    "id": "5UWwZ5lm5PKu6eKsHAGxOk",
    "title": "Everlong",
    "artist": "Foo Fighters",
    "album": "The Colour And The Shape",
    "year": "1997",
    "genre": "rock",
    "duration": "4:10",
    "popularity": 85,
    "preview_url": null,
    "coverImage": "images/5UWwZ5lm5PKu6eKsHAGxOk.jpg",
    "spotify_url": "https://open.spotify.com/track/5UWwZ5lm5PKu6eKsHAGxOk"
  },
  {
    "id": "5ghIJDpPoe3CfHMGu71E6T",
    "title": "Smells Like Teen Spirit",
    "artist": "Nirvana",
    "album": "Nevermind (Remastered)",
    "year": "1991",
    "genre": "rock",
    "duration": "5:01",
    "popularity": 81,
    "preview_url": null,
    "coverImage": "images/5ghIJDpPoe3CfHMGu71E6T.jpg",
    "spotify_url": "https://open.spotify.com/track/5ghIJDpPoe3CfHMGu71E6T"
  },
  {
    "id": "4RvWPyQ5RL0ao9LPZeSouE",
    "title": "Everybody Wants To Rule The World",
    "artist": "Tears For Fears",
    "album": "Songs From The Big Chair (Super Deluxe Edition)",
    "year": "1985",
    "genre": "rock",
    "duration": "4:11",
    "popularity": 88,
    "preview_url": null,
    "coverImage": "images/4RvWPyQ5RL0ao9LPZeSouE.jpg",
    "spotify_url": "https://open.spotify.com/track/4RvWPyQ5RL0ao9LPZeSouE"
  },
  {
    "id": "0gmbgwZ8iqyMPmXefof8Yf",
    "title": "How You Remind Me",
    "artist": "Nickelback",
    "album": "Silver Side Up",
    "year": "2001",
    "genre": "rock",
    "duration": "3:43",
    "popularity": 87,
    "preview_url": null,
    "coverImage": "images/0gmbgwZ8iqyMPmXefof8Yf.jpg",
    "spotify_url": "https://open.spotify.com/track/0gmbgwZ8iqyMPmXefof8Yf"
  },
  {
    "id": "6dOtVTDdiauQNBQEDOtlAB",
    "title": "BIRDS OF A FEATHER",
    "artist": "Billie Eilish",
    "album": "HIT ME HARD AND SOFT",
    "year": "2024",
    "genre": "pop",
    "duration": "3:30",
    "popularity": 99,
    "preview_url": null,
    "coverImage": "images/6dOtVTDdiauQNBQEDOtlAB.jpg",
    "spotify_url": "https://open.spotify.com/track/6dOtVTDdiauQNBQEDOtlAB"
  },
  {
    "id": "2plbrEY59IikOBgBGLjaoe",
    "title": "Die With A Smile",
    "artist": "Lady Gaga, Bruno Mars",
    "album": "Die With A Smile",
    "year": "2024",
    "genre": "pop",
    "duration": "4:11",
    "popularity": 100,
    "preview_url": null,
    "coverImage": "images/2plbrEY59IikOBgBGLjaoe.jpg",
    "spotify_url": "https://open.spotify.com/track/2plbrEY59IikOBgBGLjaoe"
  },
  {
    "id": "2262bWmqomIaJXwCRHr13j",
    "title": "Sailor Song",
    "artist": "Gigi Perez",
    "album": "Sailor Song",
    "year": "2024",
    "genre": "pop",
    "duration": "3:31",
    "popularity": 96,
    "preview_url": null,
    "coverImage": "images/2262bWmqomIaJXwCRHr13j.jpg",
    "spotify_url": "https://open.spotify.com/track/2262bWmqomIaJXwCRHr13j"
  },
  {
    "id": "0WbMK4wrZ1wFSty9F7FCgu",
    "title": "Good Luck, Babe!",
    "artist": "Chappell Roan",
    "album": "Good Luck, Babe!",
    "year": "2024",
    "genre": "pop",
    "duration": "3:38",
    "popularity": 95,
    "preview_url": null,
    "coverImage": "images/0WbMK4wrZ1wFSty9F7FCgu.jpg",
    "spotify_url": "https://open.spotify.com/track/0WbMK4wrZ1wFSty9F7FCgu"
  },
  {
    "id": "3siwsiaEoU4Kuuc9WKMUy5",
    "title": "No One Noticed",
    "artist": "The Marías",
    "album": "Submarine",
    "year": "2024",
    "genre": "pop",
    "duration": "3:56",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/3siwsiaEoU4Kuuc9WKMUy5.jpg",
    "spotify_url": "https://open.spotify.com/track/3siwsiaEoU4Kuuc9WKMUy5"
  },
  {
    "id": "3QaPy1KgI7nu9FJEQUgn6h",
    "title": "WILDFLOWER",
    "artist": "Billie Eilish",
    "album": "HIT ME HARD AND SOFT",
    "year": "2024",
    "genre": "pop",
    "duration": "4:21",
    "popularity": 96,
    "preview_url": null,
    "coverImage": "images/3QaPy1KgI7nu9FJEQUgn6h.jpg",
    "spotify_url": "https://open.spotify.com/track/3QaPy1KgI7nu9FJEQUgn6h"
  },
  {
    "id": "3SAga35lAPYdjj3qyfEsCF",
    "title": "Feel It - From “Invincible”",
    "artist": "d4vd",
    "album": "Feel It (From “Invincible”)",
    "year": "2024",
    "genre": "pop",
    "duration": "2:37",
    "popularity": 91,
    "preview_url": null,
    "coverImage": "images/3SAga35lAPYdjj3qyfEsCF.jpg",
    "spotify_url": "https://open.spotify.com/track/3SAga35lAPYdjj3qyfEsCF"
  },
  {
    "id": "5G2f63n7IPVPPjfNIGih7Q",
    "title": "Taste",
    "artist": "Sabrina Carpenter",
    "album": "Short n' Sweet",
    "year": "2024",
    "genre": "pop",
    "duration": "2:37",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/5G2f63n7IPVPPjfNIGih7Q.jpg",
    "spotify_url": "https://open.spotify.com/track/5G2f63n7IPVPPjfNIGih7Q"
  },
  {
    "id": "3t6gUcGYLrUuqwpXjOFWQc",
    "title": "I Never Lie",
    "artist": "Zach Top",
    "album": "Cold Beer & Country Music",
    "year": "2024",
    "genre": "pop",
    "duration": "3:44",
    "popularity": 85,
    "preview_url": null,
    "coverImage": "images/3t6gUcGYLrUuqwpXjOFWQc.jpg",
    "spotify_url": "https://open.spotify.com/track/3t6gUcGYLrUuqwpXjOFWQc"
  },
  {
    "id": "2QjOHCTQ1Jl3zawyYOpxh6",
    "title": "Sweater Weather",
    "artist": "The Neighbourhood",
    "album": "I Love You.",
    "year": "2013",
    "genre": "pop",
    "duration": "4:00",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/2QjOHCTQ1Jl3zawyYOpxh6.jpg",
    "spotify_url": "https://open.spotify.com/track/2QjOHCTQ1Jl3zawyYOpxh6"
  },
  {
    "id": "1k2pQc5i348DCHwbn5KTdc",
    "title": "Pink Pony Club",
    "artist": "Chappell Roan",
    "album": "The Rise and Fall of a Midwest Princess",
    "year": "2023",
    "genre": "pop",
    "duration": "4:18",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/1k2pQc5i348DCHwbn5KTdc.jpg",
    "spotify_url": "https://open.spotify.com/track/1k2pQc5i348DCHwbn5KTdc"
  },
  {
    "id": "3xkHsmpQCBMytMJNiDf3Ii",
    "title": "Beautiful Things",
    "artist": "Benson Boone",
    "album": "Fireworks & Rollerblades",
    "year": "2024",
    "genre": "pop",
    "duration": "3:00",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/3xkHsmpQCBMytMJNiDf3Ii.jpg",
    "spotify_url": "https://open.spotify.com/track/3xkHsmpQCBMytMJNiDf3Ii"
  },
  {
    "id": "4iZ4pt7kvcaH6Yo8UoZ4s2",
    "title": "Snooze",
    "artist": "SZA",
    "album": "SOS",
    "year": "2022",
    "genre": "pop",
    "duration": "3:21",
    "popularity": 90,
    "preview_url": null,
    "coverImage": "images/4iZ4pt7kvcaH6Yo8UoZ4s2.jpg",
    "spotify_url": "https://open.spotify.com/track/4iZ4pt7kvcaH6Yo8UoZ4s2"
  },
  {
    "id": "0mflMxspEfB0VbI1kyLiAv",
    "title": "Stick Season",
    "artist": "Noah Kahan",
    "album": "Stick Season",
    "year": "2022",
    "genre": "pop",
    "duration": "3:02",
    "popularity": 88,
    "preview_url": null,
    "coverImage": "images/0mflMxspEfB0VbI1kyLiAv.jpg",
    "spotify_url": "https://open.spotify.com/track/0mflMxspEfB0VbI1kyLiAv"
  },
  {
    "id": "6393yGahSJ9slVdOwSxOVR",
    "title": "Pink Pony Club",
    "artist": "Chappell Roan",
    "album": "The Rise and Fall of a Midwest Princess",
    "year": "2023",
    "genre": "pop",
    "duration": "4:18",
    "popularity": 88,
    "preview_url": null,
    "coverImage": "images/6393yGahSJ9slVdOwSxOVR.jpg",
    "spotify_url": "https://open.spotify.com/track/6393yGahSJ9slVdOwSxOVR"
  },
  {
    "id": "6Qyc6fS4DsZjB2mRW9DsQs",
    "title": "Iris",
    "artist": "The Goo Goo Dolls",
    "album": "Dizzy up the Girl",
    "year": "1998",
    "genre": "pop",
    "duration": "4:49",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/6Qyc6fS4DsZjB2mRW9DsQs.jpg",
    "spotify_url": "https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs"
  },
  {
    "id": "5IZXB5IKAD2qlvTPJYDCFB",
    "title": "I Had Some Help (Feat. Morgan Wallen)",
    "artist": "Post Malone, Morgan Wallen",
    "album": "F-1 Trillion",
    "year": "2024",
    "genre": "pop",
    "duration": "2:58",
    "popularity": 86,
    "preview_url": null,
    "coverImage": "images/5IZXB5IKAD2qlvTPJYDCFB.jpg",
    "spotify_url": "https://open.spotify.com/track/5IZXB5IKAD2qlvTPJYDCFB"
  },
  {
    "id": "1osfLqL6L2iQsirRf83ded",
    "title": "Worst Way",
    "artist": "Riley Green",
    "album": "Way Out Here",
    "year": "2024",
    "genre": "pop",
    "duration": "3:40",
    "popularity": 84,
    "preview_url": null,
    "coverImage": "images/1osfLqL6L2iQsirRf83ded.jpg",
    "spotify_url": "https://open.spotify.com/track/1osfLqL6L2iQsirRf83ded"
  },
  {
    "id": "1CS7Sd1u5tWkstBhpssyjP",
    "title": "Take Me to Church",
    "artist": "Hozier",
    "album": "Hozier (Expanded Edition)",
    "year": "2014",
    "genre": "pop",
    "duration": "4:01",
    "popularity": 83,
    "preview_url": null,
    "coverImage": "images/1CS7Sd1u5tWkstBhpssyjP.jpg",
    "spotify_url": "https://open.spotify.com/track/1CS7Sd1u5tWkstBhpssyjP"
  },
  {
    "id": "1UHS8Rf6h5Ar3CDWRd3wjF",
    "title": "Bed Chem",
    "artist": "Sabrina Carpenter",
    "album": "Short n' Sweet",
    "year": "2024",
    "genre": "pop",
    "duration": "2:51",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/1UHS8Rf6h5Ar3CDWRd3wjF.jpg",
    "spotify_url": "https://open.spotify.com/track/1UHS8Rf6h5Ar3CDWRd3wjF"
  },
  {
    "id": "6AI3ezQ4o3HUoP6Dhudph3",
    "title": "Not Like Us",
    "artist": "Kendrick Lamar",
    "album": "Not Like Us",
    "year": "2024",
    "genre": "hip-hop",
    "duration": "4:34",
    "popularity": 96,
    "preview_url": null,
    "coverImage": "images/6AI3ezQ4o3HUoP6Dhudph3.jpg",
    "spotify_url": "https://open.spotify.com/track/6AI3ezQ4o3HUoP6Dhudph3"
  },
  {
    "id": "3GCdLUSnKSMJhs4Tj6CV3s",
    "title": "All The Stars (with SZA)",
    "artist": "Kendrick Lamar, SZA",
    "album": "Black Panther The Album Music From And Inspired By",
    "year": "2018",
    "genre": "hip-hop",
    "duration": "3:52",
    "popularity": 95,
    "preview_url": null,
    "coverImage": "images/3GCdLUSnKSMJhs4Tj6CV3s.jpg",
    "spotify_url": "https://open.spotify.com/track/3GCdLUSnKSMJhs4Tj6CV3s"
  },
  {
    "id": "7KA4W4McWYRpgf0fWsJZWB",
    "title": "See You Again (feat. Kali Uchis)",
    "artist": "Tyler, The Creator, Kali Uchis",
    "album": "Flower Boy",
    "year": "2017",
    "genre": "hip-hop",
    "duration": "3:00",
    "popularity": 92,
    "preview_url": null,
    "coverImage": "images/7KA4W4McWYRpgf0fWsJZWB.jpg",
    "spotify_url": "https://open.spotify.com/track/7KA4W4McWYRpgf0fWsJZWB"
  },
  {
    "id": "3xKsf9qdS1CyvXSMEid6g8",
    "title": "Pink + White",
    "artist": "Frank Ocean",
    "album": "Blonde",
    "year": "2016",
    "genre": "hip-hop",
    "duration": "3:04",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/3xKsf9qdS1CyvXSMEid6g8.jpg",
    "spotify_url": "https://open.spotify.com/track/3xKsf9qdS1CyvXSMEid6g8"
  },
  {
    "id": "2tudvzsrR56uom6smgOcSf",
    "title": "Like That",
    "artist": "Future, Metro Boomin, Kendrick Lamar",
    "album": "WE DON'T TRUST YOU",
    "year": "2024",
    "genre": "hip-hop",
    "duration": "4:27",
    "popularity": 88,
    "preview_url": null,
    "coverImage": "images/2tudvzsrR56uom6smgOcSf.jpg",
    "spotify_url": "https://open.spotify.com/track/2tudvzsrR56uom6smgOcSf"
  },
  {
    "id": "2HbKqm4o0w5wEeEFXm2sD4",
    "title": "Money Trees",
    "artist": "Kendrick Lamar, Jay Rock",
    "album": "good kid, m.A.A.d city",
    "year": "2012",
    "genre": "hip-hop",
    "duration": "6:26",
    "popularity": 84,
    "preview_url": null,
    "coverImage": "images/2HbKqm4o0w5wEeEFXm2sD4.jpg",
    "spotify_url": "https://open.spotify.com/track/2HbKqm4o0w5wEeEFXm2sD4"
  },
  {
    "id": "7KXjTSCq5nL1LoYtL7XAwS",
    "title": "HUMBLE.",
    "artist": "Kendrick Lamar",
    "album": "DAMN.",
    "year": "2017",
    "genre": "hip-hop",
    "duration": "2:57",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/7KXjTSCq5nL1LoYtL7XAwS.jpg",
    "spotify_url": "https://open.spotify.com/track/7KXjTSCq5nL1LoYtL7XAwS"
  },
  {
    "id": "3ESSGgWzRf1xvP7G5hHMhB",
    "title": "Again",
    "artist": "Fetty Wap",
    "album": "Fetty Wap (Deluxe)",
    "year": "2015",
    "genre": "hip-hop",
    "duration": "5:12",
    "popularity": 83,
    "preview_url": null,
    "coverImage": "images/3ESSGgWzRf1xvP7G5hHMhB.jpg",
    "spotify_url": "https://open.spotify.com/track/3ESSGgWzRf1xvP7G5hHMhB"
  },
  {
    "id": "7DfFc7a6Rwfi3YQMRbDMau",
    "title": "Thinkin Bout You",
    "artist": "Frank Ocean",
    "album": "channel ORANGE",
    "year": "2012",
    "genre": "hip-hop",
    "duration": "3:20",
    "popularity": 87,
    "preview_url": null,
    "coverImage": "images/7DfFc7a6Rwfi3YQMRbDMau.jpg",
    "spotify_url": "https://open.spotify.com/track/7DfFc7a6Rwfi3YQMRbDMau"
  },
  {
    "id": "1XBYiRV30ykHw5f4wm6qEn",
    "title": "NIGHTS LIKE THIS",
    "artist": "The Kid LAROI",
    "album": "THE FIRST TIME",
    "year": "2023",
    "genre": "hip-hop",
    "duration": "1:26",
    "popularity": 88,
    "preview_url": null,
    "coverImage": "images/1XBYiRV30ykHw5f4wm6qEn.jpg",
    "spotify_url": "https://open.spotify.com/track/1XBYiRV30ykHw5f4wm6qEn"
  },
  {
    "id": "68Dni7IE4VyPkTOH9mRWHr",
    "title": "No Role Modelz",
    "artist": "J. Cole",
    "album": "2014 Forest Hills Drive",
    "year": "2014",
    "genre": "hip-hop",
    "duration": "4:52",
    "popularity": 87,
    "preview_url": null,
    "coverImage": "images/68Dni7IE4VyPkTOH9mRWHr.jpg",
    "spotify_url": "https://open.spotify.com/track/68Dni7IE4VyPkTOH9mRWHr"
  },
  {
    "id": "0d28khcov6AiegSCpG5TuT",
    "title": "Feel Good Inc.",
    "artist": "Gorillaz, De La Soul",
    "album": "Demon Days",
    "year": "2005",
    "genre": "hip-hop",
    "duration": "3:42",
    "popularity": 89,
    "preview_url": null,
    "coverImage": "images/0d28khcov6AiegSCpG5TuT.jpg",
    "spotify_url": "https://open.spotify.com/track/0d28khcov6AiegSCpG5TuT"
  },
  {
    "id": "6PGoSes0D9eUDeeAafB2As",
    "title": "LOVE. FEAT. ZACARI.",
    "artist": "Kendrick Lamar, Zacari",
    "album": "DAMN.",
    "year": "2017",
    "genre": "hip-hop",
    "duration": "3:33",
    "popularity": 87,
    "preview_url": null,
    "coverImage": "images/6PGoSes0D9eUDeeAafB2As.jpg",
    "spotify_url": "https://open.spotify.com/track/6PGoSes0D9eUDeeAafB2As"
  },
  {
    "id": "2d8JP84HNLKhmd6IYOoupQ",
    "title": "Trap Queen",
    "artist": "Fetty Wap",
    "album": "Fetty Wap (Deluxe)",
    "year": "2015",
    "genre": "hip-hop",
    "duration": "3:42",
    "popularity": 84,
    "preview_url": null,
    "coverImage": "images/2d8JP84HNLKhmd6IYOoupQ.jpg",
    "spotify_url": "https://open.spotify.com/track/2d8JP84HNLKhmd6IYOoupQ"
  },
  {
    "id": "0SA0mMXWh23raZ6xzOCU2V",
    "title": "She",
    "artist": "Tyler, The Creator, Frank Ocean",
    "album": "Goblin",
    "year": "2011",
    "genre": "hip-hop",
    "duration": "4:13",
    "popularity": 80,
    "preview_url": null,
    "coverImage": "images/0SA0mMXWh23raZ6xzOCU2V.jpg",
    "spotify_url": "https://open.spotify.com/track/0SA0mMXWh23raZ6xzOCU2V"
  },
  {
    "id": "3pXF1nA74528Edde4of9CC",
    "title": "Don't",
    "artist": "Bryson Tiller",
    "album": "T R A P S O U L",
    "year": "2015",
    "genre": "hip-hop",
    "duration": "3:18",
    "popularity": 86,
    "preview_url": null,
    "coverImage": "images/3pXF1nA74528Edde4of9CC.jpg",
    "spotify_url": "https://open.spotify.com/track/3pXF1nA74528Edde4of9CC"
  },
  {
    "id": "2ZWlPOoWh0626oTaHrnl2a",
    "title": "Ivy",
    "artist": "Frank Ocean",
    "album": "Blonde",
    "year": "2016",
    "genre": "hip-hop",
    "duration": "4:09",
    "popularity": 86,
    "preview_url": null,
    "coverImage": "images/2ZWlPOoWh0626oTaHrnl2a.jpg",
    "spotify_url": "https://open.spotify.com/track/2ZWlPOoWh0626oTaHrnl2a"
  },
  {
    "id": "7FAFkQQZFeNwOFzTrSDFIh",
    "title": "The Spins",
    "artist": "Mac Miller, Empire Of The Sun",
    "album": "K.I.D.S. (Deluxe)",
    "year": "2010",
    "genre": "hip-hop",
    "duration": "3:15",
    "popularity": 86,
    "preview_url": null,
    "coverImage": "images/7FAFkQQZFeNwOFzTrSDFIh.jpg",
    "spotify_url": "https://open.spotify.com/track/7FAFkQQZFeNwOFzTrSDFIh"
  },
  {
    "id": "4osgfFTICMkcGbbigdsa53",
    "title": "Novacane",
    "artist": "Frank Ocean",
    "album": "Novacane",
    "year": "2011",
    "genre": "hip-hop",
    "duration": "5:02",
    "popularity": 84,
    "preview_url": null,
    "coverImage": "images/4osgfFTICMkcGbbigdsa53.jpg",
    "spotify_url": "https://open.spotify.com/track/4osgfFTICMkcGbbigdsa53"
  },
  {
    "id": "3ZaEs1O8BG581qYPHpQ8d6",
    "title": "I Smoked Away My Brain (I'm God x Demons Mashup) (feat. Imogen Heap & Clams Casino)",
    "artist": "A$AP Rocky, Imogen Heap, Clams Casino",
    "album": "I Smoked Away My Brain (I'm God x Demons Mashup) (feat. Imogen Heap & Clams Casino)",
    "year": "2023",
    "genre": "hip-hop",
    "duration": "3:10",
    "popularity": 87,
    "preview_url": null,
    "coverImage": "images/3ZaEs1O8BG581qYPHpQ8d6.jpg",
    "spotify_url": "https://open.spotify.com/track/3ZaEs1O8BG581qYPHpQ8d6"
  },
  {
    "id": "3kXoKlD84c6OmIcOLfrfEs",
    "title": "September",
    "artist": "Earth, Wind & Fire",
    "album": "September (sped up + slowed)",
    "year": "1978",
    "genre": "jazz",
    "duration": "3:36",
    "popularity": 84,
    "preview_url": null,
    "coverImage": "images/3kXoKlD84c6OmIcOLfrfEs.jpg",
    "spotify_url": "https://open.spotify.com/track/3kXoKlD84c6OmIcOLfrfEs"
  },
  {
    "id": "3koCCeSaVUyrRo3N2gHrd8",
    "title": "Let's Groove",
    "artist": "Earth, Wind & Fire",
    "album": "Raise!",
    "year": "1981",
    "genre": "jazz",
    "duration": "5:39",
    "popularity": 82,
    "preview_url": null,
    "coverImage": "images/3koCCeSaVUyrRo3N2gHrd8.jpg",
    "spotify_url": "https://open.spotify.com/track/3koCCeSaVUyrRo3N2gHrd8"
  },
  {
    "id": "3zBhihYUHBmGd2bcQIobrF",
    "title": "(Sittin' On) the Dock of the Bay",
    "artist": "Otis Redding",
    "album": "The Dock of the Bay (Mono)",
    "year": "1968",
    "genre": "jazz",
    "duration": "2:43",
    "popularity": 79,
    "preview_url": null,
    "coverImage": "images/3zBhihYUHBmGd2bcQIobrF.jpg",
    "spotify_url": "https://open.spotify.com/track/3zBhihYUHBmGd2bcQIobrF"
  },
  {
    "id": "6ztstiyZL6FXzh4aG46ZPD",
    "title": "Boogie Wonderland",
    "artist": "Earth, Wind & Fire, The Emotions",
    "album": "I Am",
    "year": "1979",
    "genre": "jazz",
    "duration": "4:48",
    "popularity": 81,
    "preview_url": null,
    "coverImage": "images/6ztstiyZL6FXzh4aG46ZPD.jpg",
    "spotify_url": "https://open.spotify.com/track/6ztstiyZL6FXzh4aG46ZPD"
  },
  {
    "id": "7EqpEBPOohgk7NnKvBGFWo",
    "title": "Wait for It",
    "artist": "Leslie Odom Jr., Original Broadway Cast of Hamilton",
    "album": "Hamilton (Original Broadway Cast Recording)",
    "year": "2015",
    "genre": "jazz",
    "duration": "3:13",
    "popularity": 75,
    "preview_url": null,
    "coverImage": "images/7EqpEBPOohgk7NnKvBGFWo.jpg",
    "spotify_url": "https://open.spotify.com/track/7EqpEBPOohgk7NnKvBGFWo"
  },
  {
    "id": "1kPBT8S2wJFNAyBMnGVZgL",
    "title": "I'd Rather Go Blind",
    "artist": "Etta James",
    "album": "Tell Mama",
    "year": "1968",
    "genre": "jazz",
    "duration": "2:36",
    "popularity": 78,
    "preview_url": null,
    "coverImage": "images/1kPBT8S2wJFNAyBMnGVZgL.jpg",
    "spotify_url": "https://open.spotify.com/track/1kPBT8S2wJFNAyBMnGVZgL"
  },
  {
    "id": "4Hhv2vrOTy89HFRcjU3QOx",
    "title": "At Last",
    "artist": "Etta James",
    "album": "At Last!",
    "year": "1960",
    "genre": "jazz",
    "duration": "2:59",
    "popularity": 78,
    "preview_url": null,
    "coverImage": "images/4Hhv2vrOTy89HFRcjU3QOx.jpg",
    "spotify_url": "https://open.spotify.com/track/4Hhv2vrOTy89HFRcjU3QOx"
  },
  {
    "id": "4TTV7EcfroSLWzXRY6gLv6",
    "title": "Alexander Hamilton",
    "artist": "Leslie Odom Jr., Daveed Diggs, Okieriete Onaodowan, Lin-Manuel Miranda, Phillipa Soo, Christopher Jackson, Original Broadway Cast of Hamilton, Anthony Ramos",
    "album": "Hamilton (Original Broadway Cast Recording)",
    "year": "2015",
    "genre": "jazz",
    "duration": "3:56",
    "popularity": 74,
    "preview_url": null,
    "coverImage": "images/4TTV7EcfroSLWzXRY6gLv6.jpg",
    "spotify_url": "https://open.spotify.com/track/4TTV7EcfroSLWzXRY6gLv6"
  },
  {
    "id": "1zNXF2svmdlNxfS5XeNUgr",
    "title": "Don't Know Why",
    "artist": "Norah Jones",
    "album": "Come Away With Me (Super Deluxe Edition)",
    "year": "2002",
    "genre": "jazz",
    "duration": "3:06",
    "popularity": 79,
    "preview_url": null,
    "coverImage": "images/1zNXF2svmdlNxfS5XeNUgr.jpg",
    "spotify_url": "https://open.spotify.com/track/1zNXF2svmdlNxfS5XeNUgr"
  },
  {
    "id": "1ko2lVN0vKGUl9zrU0qSlT",
    "title": "Just the Two of Us (feat. Bill Withers)",
    "artist": "Grover Washington, Jr., Bill Withers",
    "album": "Anthology",
    "year": "1985",
    "genre": "jazz",
    "duration": "7:18",
    "popularity": 77,
    "preview_url": null,
    "coverImage": "images/1ko2lVN0vKGUl9zrU0qSlT.jpg",
    "spotify_url": "https://open.spotify.com/track/1ko2lVN0vKGUl9zrU0qSlT"
  },
  {
    "id": "3I09LQbHS3NSU46Ly3tPpR",
    "title": "Feeling Good",
    "artist": "Michael Bublé",
    "album": "It's Time",
    "year": "2005",
    "genre": "jazz",
    "duration": "3:57",
    "popularity": 70,
    "preview_url": null,
    "coverImage": "images/3I09LQbHS3NSU46Ly3tPpR.jpg",
    "spotify_url": "https://open.spotify.com/track/3I09LQbHS3NSU46Ly3tPpR"
  },
  {
    "id": "29U7stRjqHU6rMiS8BfaI9",
    "title": "What A Wonderful World",
    "artist": "Louis Armstrong",
    "album": "What A Wonderful World",
    "year": "1968",
    "genre": "jazz",
    "duration": "2:19",
    "popularity": 78,
    "preview_url": null,
    "coverImage": "images/29U7stRjqHU6rMiS8BfaI9.jpg",
    "spotify_url": "https://open.spotify.com/track/29U7stRjqHU6rMiS8BfaI9"
  },
  {
    "id": "2grjqo0Frpf2okIBiifQKs",
    "title": "September",
    "artist": "Earth, Wind & Fire",
    "album": "The Best Of Earth, Wind & Fire Vol. 1",
    "year": "1978",
    "genre": "jazz",
    "duration": "3:35",
    "popularity": 76,
    "preview_url": null,
    "coverImage": "images/2grjqo0Frpf2okIBiifQKs.jpg",
    "spotify_url": "https://open.spotify.com/track/2grjqo0Frpf2okIBiifQKs"
  },
  {
    "id": "4QxDOjgpYtQDxxbWPuEJOy",
    "title": "L-O-V-E",
    "artist": "Nat King Cole",
    "album": "L-O-V-E",
    "year": "1965",
    "genre": "jazz",
    "duration": "2:35",
    "popularity": 76,
    "preview_url": null,
    "coverImage": "images/4QxDOjgpYtQDxxbWPuEJOy.jpg",
    "spotify_url": "https://open.spotify.com/track/4QxDOjgpYtQDxxbWPuEJOy"
  },
  {
    "id": "7odHgoLFi3GQ90E9PeraI3",
    "title": "Son of a Preacher Man",
    "artist": "Dusty Springfield",
    "album": "Dusty In Memphis [Deluxe Edition]",
    "year": "1969",
    "genre": "jazz",
    "duration": "2:29",
    "popularity": 67,
    "preview_url": null,
    "coverImage": "images/7odHgoLFi3GQ90E9PeraI3.jpg",
    "spotify_url": "https://open.spotify.com/track/7odHgoLFi3GQ90E9PeraI3"
  },
  {
    "id": "3KzgdYUlqV6TOG7JCmx2Wg",
    "title": "Beyond the Sea",
    "artist": "Bobby Darin",
    "album": "That's All",
    "year": "1959",
    "genre": "jazz",
    "duration": "2:52",
    "popularity": 72,
    "preview_url": null,
    "coverImage": "images/3KzgdYUlqV6TOG7JCmx2Wg.jpg",
    "spotify_url": "https://open.spotify.com/track/3KzgdYUlqV6TOG7JCmx2Wg"
  },
  {
    "id": "0zGLlXbHlrAyBN1x6sY0rb",
    "title": "A Sunday Kind Of Love",
    "artist": "Etta James",
    "album": "At Last!",
    "year": "1960",
    "genre": "jazz",
    "duration": "3:16",
    "popularity": 73,
    "preview_url": null,
    "coverImage": "images/0zGLlXbHlrAyBN1x6sY0rb.jpg",
    "spotify_url": "https://open.spotify.com/track/0zGLlXbHlrAyBN1x6sY0rb"
  },
  {
    "id": "3NfxSdJnVdon1axzloJgba",
    "title": "I Say a Little Prayer",
    "artist": "Aretha Franklin",
    "album": "Aretha Now",
    "year": "1968",
    "genre": "jazz",
    "duration": "3:36",
    "popularity": 78,
    "preview_url": null,
    "coverImage": "images/3NfxSdJnVdon1axzloJgba.jpg",
    "spotify_url": "https://open.spotify.com/track/3NfxSdJnVdon1axzloJgba"
  },
  {
    "id": "3gsCAGsWr6pUm1Vy7CPPob",
    "title": "Killing Me Softly With His Song",
    "artist": "Roberta Flack",
    "album": "Killing Me Softly",
    "year": "1973",
    "genre": "jazz",
    "duration": "4:46",
    "popularity": 77,
    "preview_url": null,
    "coverImage": "images/3gsCAGsWr6pUm1Vy7CPPob.jpg",
    "spotify_url": "https://open.spotify.com/track/3gsCAGsWr6pUm1Vy7CPPob"
  },
  {
    "id": "6jGnykaS6TkWp15utXSAeI",
    "title": "Come Away With Me",
    "artist": "Norah Jones",
    "album": "Come Away With Me (Super Deluxe Edition)",
    "year": "2002",
    "genre": "jazz",
    "duration": "3:18",
    "popularity": 75,
    "preview_url": null,
    "coverImage": "images/6jGnykaS6TkWp15utXSAeI.jpg",
    "spotify_url": "https://open.spotify.com/track/6jGnykaS6TkWp15utXSAeI"
  },
  {
    "id": "0lYBSQXN6rCTvUZvg9S0lU",
    "title": "Let Me Love You",
    "artist": "DJ Snake, Justin Bieber",
    "album": "Encore",
    "year": "2016",
    "genre": "electronic",
    "duration": "3:25",
    "popularity": 87,
    "preview_url": null,
    "coverImage": "images/0lYBSQXN6rCTvUZvg9S0lU.jpg",
    "spotify_url": "https://open.spotify.com/track/0lYBSQXN6rCTvUZvg9S0lU"
  },
  {
    "id": "3aMIgXaB04SzL68n4lMWLL",
    "title": "Tom Tom",
    "artist": "Holy F*ck",
    "album": "Congrats",
    "year": "2016",
    "genre": "electronic",
    "duration": "3:47",
    "popularity": 78,
    "preview_url": null,
    "coverImage": "images/3aMIgXaB04SzL68n4lMWLL.jpg",
    "spotify_url": "https://open.spotify.com/track/3aMIgXaB04SzL68n4lMWLL"
  },
  {
    "id": "5mc6EyF1OIEOhAkD0Gg9Lc",
    "title": "Closer",
    "artist": "Nine Inch Nails",
    "album": "The Downward Spiral (Deluxe Edition)",
    "year": "1994",
    "genre": "electronic",
    "duration": "6:13",
    "popularity": 75,
    "preview_url": null,
    "coverImage": "images/5mc6EyF1OIEOhAkD0Gg9Lc.jpg",
    "spotify_url": "https://open.spotify.com/track/5mc6EyF1OIEOhAkD0Gg9Lc"
  },
  {
    "id": "57kR5SniQIbsbVoIjjOUDa",
    "title": "You Know You Like It",
    "artist": "DJ Snake, AlunaGeorge",
    "album": "You Know You Like It",
    "year": "2014",
    "genre": "electronic",
    "duration": "4:07",
    "popularity": 75,
    "preview_url": null,
    "coverImage": "images/57kR5SniQIbsbVoIjjOUDa.jpg",
    "spotify_url": "https://open.spotify.com/track/57kR5SniQIbsbVoIjjOUDa"
  },
  {
    "id": "0g5EKLgdKvNlln7TNqBByK",
    "title": "Middle",
    "artist": "DJ Snake, Bipolar Sunshine",
    "album": "Encore",
    "year": "2016",
    "genre": "electronic",
    "duration": "3:40",
    "popularity": 79,
    "preview_url": null,
    "coverImage": "images/0g5EKLgdKvNlln7TNqBByK.jpg",
    "spotify_url": "https://open.spotify.com/track/0g5EKLgdKvNlln7TNqBByK"
  },
  {
    "id": "7uv632EkfwYhXoqf8rhYrg",
    "title": "Angel",
    "artist": "Massive Attack, Horace Andy",
    "album": "Mezzanine",
    "year": "1998",
    "genre": "electronic",
    "duration": "6:19",
    "popularity": 78,
    "preview_url": null,
    "coverImage": "images/7uv632EkfwYhXoqf8rhYrg.jpg",
    "spotify_url": "https://open.spotify.com/track/7uv632EkfwYhXoqf8rhYrg"
  },
  {
    "id": "6G15l720kBWvIQZyoEJEYE",
    "title": "Alibi (with Pabllo Vittar & Yseult)",
    "artist": "Sevdaliza, Pabllo Vittar, Yseult",
    "album": "Alibi (with Pabllo Vittar & Yseult)",
    "year": "2024",
    "genre": "electronic",
    "duration": "2:41",
    "popularity": 68,
    "preview_url": null,
    "coverImage": "images/6G15l720kBWvIQZyoEJEYE.jpg",
    "spotify_url": "https://open.spotify.com/track/6G15l720kBWvIQZyoEJEYE"
  },
  {
    "id": "5oYVxFt2k4SkVp6wzVsFWN",
    "title": "Ride Or Die, Pt. 2 (with Villano Antillano & Tokischa)",
    "artist": "Sevdaliza, Villano Antillano, Tokischa",
    "album": "Ride Or Die, Pt. 2",
    "year": "2024",
    "genre": "electronic",
    "duration": "2:38",
    "popularity": 84,
    "preview_url": null,
    "coverImage": "images/5oYVxFt2k4SkVp6wzVsFWN.jpg",
    "spotify_url": "https://open.spotify.com/track/5oYVxFt2k4SkVp6wzVsFWN"
  },
  {
    "id": "0ITaSRuI0L1RNL7ZNYTTi7",
    "title": "U Are My High (with Future)",
    "artist": "DJ Snake, Future",
    "album": "U Are My High (with Future)",
    "year": "2021",
    "genre": "electronic",
    "duration": "3:31",
    "popularity": 75,
    "preview_url": null,
    "coverImage": "images/0ITaSRuI0L1RNL7ZNYTTi7.jpg",
    "spotify_url": "https://open.spotify.com/track/0ITaSRuI0L1RNL7ZNYTTi7"
  },
  {
    "id": "3Ty7OTBNSigGEpeW2PqcsC",
    "title": "Glory Box",
    "artist": "Portishead",
    "album": "Dummy",
    "year": "1994",
    "genre": "electronic",
    "duration": "5:08",
    "popularity": 77,
    "preview_url": null,
    "coverImage": "images/3Ty7OTBNSigGEpeW2PqcsC.jpg",
    "spotify_url": "https://open.spotify.com/track/3Ty7OTBNSigGEpeW2PqcsC"
  },
  {
    "id": "5ugzDiilhy6ILKmKfhEzd7",
    "title": "The Hand That Feeds",
    "artist": "Nine Inch Nails",
    "album": "With Teeth",
    "year": "2005",
    "genre": "electronic",
    "duration": "3:31",
    "popularity": 67,
    "preview_url": null,
    "coverImage": "images/5ugzDiilhy6ILKmKfhEzd7.jpg",
    "spotify_url": "https://open.spotify.com/track/5ugzDiilhy6ILKmKfhEzd7"
  },
  {
    "id": "3aQ9MHkMeL7Yu7jpyF62xn",
    "title": "Neverender",
    "artist": "Justice, Tame Impala",
    "album": "Hyperdrama",
    "year": "2024",
    "genre": "electronic",
    "duration": "4:26",
    "popularity": 73,
    "preview_url": null,
    "coverImage": "images/3aQ9MHkMeL7Yu7jpyF62xn.jpg",
    "spotify_url": "https://open.spotify.com/track/3aQ9MHkMeL7Yu7jpyF62xn"
  },
  {
    "id": "784VjdNkpXhFV0RHquzsi2",
    "title": "100",
    "artist": "Dean Blunt",
    "album": "BLACK METAL",
    "year": "2014",
    "genre": "electronic",
    "duration": "3:20",
    "popularity": 70,
    "preview_url": null,
    "coverImage": "images/784VjdNkpXhFV0RHquzsi2.jpg",
    "spotify_url": "https://open.spotify.com/track/784VjdNkpXhFV0RHquzsi2"
  },
  {
    "id": "67awxiNHNyjMXhVgsHuIrs",
    "title": "Turn Down for What",
    "artist": "DJ Snake, Lil Jon",
    "album": "Turn Down for What",
    "year": "2013",
    "genre": "electronic",
    "duration": "3:33",
    "popularity": 72,
    "preview_url": null,
    "coverImage": "images/67awxiNHNyjMXhVgsHuIrs.jpg",
    "spotify_url": "https://open.spotify.com/track/67awxiNHNyjMXhVgsHuIrs"
  },
  {
    "id": "2qLSXZuIHMsKydCEFDchc3",
    "title": "Bang Bang Bang Bang",
    "artist": "Sohodolls",
    "album": "Ribbed Music For The Numb Generation",
    "year": "2007",
    "genre": "electronic",
    "duration": "3:01",
    "popularity": 65,
    "preview_url": null,
    "coverImage": "images/2qLSXZuIHMsKydCEFDchc3.jpg",
    "spotify_url": "https://open.spotify.com/track/2qLSXZuIHMsKydCEFDchc3"
  },
  {
    "id": "5JXtkWtuqS8Dm8sKbtPGWa",
    "title": "9",
    "artist": "Dean Blunt, Panda Bear",
    "album": "ZUSHI",
    "year": "2020",
    "genre": "electronic",
    "duration": "1:27",
    "popularity": 68,
    "preview_url": null,
    "coverImage": "images/5JXtkWtuqS8Dm8sKbtPGWa.jpg",
    "spotify_url": "https://open.spotify.com/track/5JXtkWtuqS8Dm8sKbtPGWa"
  },
  {
    "id": "0ypg59NyOVCpWVzd0SUsT5",
    "title": "Every Day Is Exactly The Same",
    "artist": "Nine Inch Nails",
    "album": "With Teeth",
    "year": "2005",
    "genre": "electronic",
    "duration": "4:54",
    "popularity": 65,
    "preview_url": null,
    "coverImage": "images/0ypg59NyOVCpWVzd0SUsT5.jpg",
    "spotify_url": "https://open.spotify.com/track/0ypg59NyOVCpWVzd0SUsT5"
  },
  {
    "id": "2cmRpmO04TLaKPzmAzySYZ",
    "title": "Dance Yrself Clean",
    "artist": "LCD Soundsystem",
    "album": "This Is Happening",
    "year": "2010",
    "genre": "electronic",
    "duration": "8:56",
    "popularity": 67,
    "preview_url": null,
    "coverImage": "images/2cmRpmO04TLaKPzmAzySYZ.jpg",
    "spotify_url": "https://open.spotify.com/track/2cmRpmO04TLaKPzmAzySYZ"
  },
  {
    "id": "1KOqY0QTSadQFRgbNw1sLh",
    "title": "Never Catch Me",
    "artist": "Flying Lotus, Kendrick Lamar",
    "album": "You're Dead!",
    "year": "2014",
    "genre": "electronic",
    "duration": "3:54",
    "popularity": 68,
    "preview_url": null,
    "coverImage": "images/1KOqY0QTSadQFRgbNw1sLh.jpg",
    "spotify_url": "https://open.spotify.com/track/1KOqY0QTSadQFRgbNw1sLh"
  },
  {
    "id": "6osaMSJh9NguagEDQcZaKx",
    "title": "Loco Contigo (feat. J. Balvin & Tyga)",
    "artist": "DJ Snake, J Balvin, Tyga",
    "album": "Carte Blanche",
    "year": "2019",
    "genre": "electronic",
    "duration": "3:05",
    "popularity": 77,
    "preview_url": null,
    "coverImage": "images/6osaMSJh9NguagEDQcZaKx.jpg",
    "spotify_url": "https://open.spotify.com/track/6osaMSJh9NguagEDQcZaKx"
  }
];

export default musicCatalog;